### ISSUE TITLE
Lizenzbilder für Deckblätter automatisch abhängig vom Dokument auswählen

### ISSUE THREAD

**Issue by j3nsch** [OPUS4/opus4-pdf#22]
Das Lizenzbild im Deckblatt-Template muss abhängig vom Dokument generiert werden.

**Comment by j3nsch** [comment]
Die Lizenzbilder könnten erst einmal unter `public/img/licences` abgelegt werden. Später wäre es sinnvoll das Anlegen bzw. automatische Herunterladen dieser Bilder mit in die Lizenzverwaltung zu integrieren. Dort wird ja bereits eine URL für das Lizenzbild angegeben. Das wäre aber ein neue Aufgabe für die Erweiterung der Lizenzverwaltung und sollte durch Issues in `Application` festgehalten werden.

**Comment by extracts** [comment]
Der Pfad zum `public/img/licences` Verzeichnis, welches die Lizenzbilder enthält, könnte ähnlich wie der `images-basepath` an Pandoc übergeben werden:
```
--variable=licence-images-path:public/img/licences/
```
In der Template steht der Pfad dann über die Variable `$licence-images-path$` zur Verfügung. Die bei der Deckblatt-Generierung erstellte Metadaten-Datei (`meta.json`) würde dann lediglich den Dateinamen des Lizenzbildes enthalten.

Alternativ könnte die Metadaten-Datei einfach den vollen Pfad zum Lizenzbild enthalten.

**Comment by extracts** [comment]
Siehe auch OPUS4/opus4-licences#5 (Defaultverzeichnis für Lizenz-Logos definieren)

**Comment by extracts** [comment]
Das Verzeichnis für Lizenzlogos kann nun über die Konfigurationsoption `licences.logos.path` angegeben werden. Siehe dazu auch ["Anzeigen-von-lizenzlogos"](https://github.com/OPUS4/opus4-pdf/blob/issue39/LIESMICH.md#anzeigen-von-lizenzlogos) in der Paket-Dokumentation.
