### ISSUE TITLE
PDFs mit Deckblatt in separatem Verzeichnis speichern

### ISSUE THREAD

**Issue by j3nsch** [OPUS4/opus4-pdf#42]
Momentan landen die generierten PDFs in `workspace/tmp` gespeichert. Dieses Verzeichnis ist für wirklich temporäre Dateien gedacht und wird regelmäßig bereinigt. Die PDFs mit Deckblatt müssen nur erneuert werden, wenn sich die Metadaten eines Dokuments verändert haben. Sie sollten in einem separaten Verzeichnis gespeichert werden, z.B. `workspace/filecache` oder `workspace/covercache`. 

Es ist klar, dass es eigentlich ein "PDFmitCoverCache"-Verzeichnis ist, aber der Name sollte vereinfacht werden.

**Comment by extracts** [comment]
Das mit dem Original-PDF zusammengefügte Deckblatt wird bereits in `workspace/filecache` gecached und ausgeliefert, solange sich die Metadaten des verknüpften Dokuments nicht ändern.

Lediglich das generierte Deckblatt (vor dem Merge mit dem Original-PDF) landet in `workspace/tmp`. Dies ist eine temporäre Datei, die (nach dem Merge mit dem Original-PDF) nicht mehr benötigt wird und im Zuge der regelmässigen Bereinigung entfernt werden kann. Wenn sich die Metadaten des Dokuments ändern, muss dann eh ein neues Deckblatt generiert werden.
