### ISSUE TITLE
Vagrantfile für Entwicklung hinzufügen

### ISSUE THREAD

**Issue by extracts** [OPUS4/opus4-pdf#5]
Mit [Vagrant](https://www.vagrantup.com/) lässt sich eine Entwicklungsumgebung in einer VM hochfahren, so dass die notwendigen Tools und Ressourcen nicht im Host-System installiert werden müssen.

**Comment by j3nsch** [comment]
Die Hilfe geht davon aus, dass man 'composer' direkt aufrufen kann. Ich denke, dass sollten wir auch so machen. Wir müssen dafür entweder das  `install-composer.sh` Skript vom Framework kopieren oder Composer mit apt-get installieren. Dann verwenden wir allerdings Version 1.x. Bei der Application geht das nicht, aber hier wäre es vermutlich im Augenblick okay.

**Comment by j3nsch** [comment]
Wir müssen auch die PHP-Pakete für Composer installieren. Das sind Curl und Zip. Ist DOM eine Abhängigkeit vom OPUS 4 PHP Code? Wenn ja, muss das auch in `composer.json` deklariert werden.

**Comment by j3nsch** [comment]
Ich mache die Anpassungen an `Vagrantfile`.

**Comment by j3nsch** [comment]
In habe auch noch `unzip` installiert, weil Composer lieber damit arbeitet.

**Comment by j3nsch** [comment]
Vagrantfile ist konfiguriert.
