### ISSUE TITLE
Kommando zur Cover-Generierung auf der Kommandozeile

### ISSUE THREAD

**Issue by extracts** [OPUS4/opus4-pdf#50]
Zum Testen und Debuggen während der Entwicklung einer eigenen PDF Deckblatt-Vorlage kann es hilfreich sein, manuell direkt mit Pandoc and XeTeX ein PDF Deckblatt generieren zu können. Dazu könnte ein Kommando erstellt werden, welches folgende pandoc Befehle ausführen könnte:
```
# - A template can be converted to a PDF cover manually using Pandoc and XeTeX via two steps:
#   
#   - when using a single .yaml file containing both, general and bibliographic metadata:
#     - `pandoc /PATH/TO/TEMPLATE_DIR/cover-template.md /PATH/TO/metadata.yaml --wrap=preserve --bibliography=/PATH/TO/metadata.yaml --template=/PATH/TO/TEMPLATE_DIR/cover-template.md --variable=images-basepath:/PATH/TO/TEMPLATE_DIR/ --variable=licence-logo-basepath:/PATH/TO/LICENCE_LOGO_DIR/ --output=cover.md`
#     - `pandoc cover.md --resource-path=/PATH/TO/TEMPLATE_DIR/ --bibliography=/PATH/TO/metadata.yaml --citeproc --pdf-engine=xelatex --pdf-engine-opt=-output-driver="xdvipdfmx -V 3 -z 0" --output=cover.pdf`
#   
#   - when using separate .json files for general and bibliographic metadata:
#     - `pandoc /PATH/TO/TEMPLATE_DIR/cover-template.md --wrap=preserve --metadata-file=/PATH/TO/meta.json --bibliography=/PATH/TO/csl.json --template=/PATH/TO/TEMPLATE_DIR/cover-template.md --variable=images-basepath:/PATH/TO/TEMPLATE_DIR/ --variable=licence-logo-basepath:/PATH/TO/LICENCE_LOGO_DIR/ --output=cover.md`
#     - `pandoc cover.md --resource-path=/PATH/TO/TEMPLATE_DIR/ --bibliography=/PATH/TO/csl.json --citeproc --pdf-engine=xelatex --pdf-engine-opt=-output-driver="xdvipdfmx -V 3 -z 0" --output=cover.pdf`
#   
# - As in the examples above, this template requires two calls to pandoc with the following arguments:
#   - `--wrap=` set to `preserve` which causes Pandoc to preserve the line wrapping from this template file
#   - `--metadata-file=` set to the path of the metadata file containing the document's general metadata
#   - `--bibliography=` set to the path of the metadata file containing the document's bibliographic metadata
#   - `--template=` set to the path of this template file
#   - `--variable=` set to `images-basepath:` and followed by the base path of the `images` subdirectory containing images used by this template
#   - `--variable=` set to `licence-logo-basepath:` and followed by the path to a directory containing licence logos (arranged/named according to <https://licensebuttons.net>)
#   - `--resource-path=` set to the base path of the `styles` subdirectory containing the citation style used by this template
#   - `--citeproc` which causes a formatted citation to be generated from the bibliographic metadata
#   - `--pdf-engine=` set to `xelatex` which specifies that XeTeX will be used to generate the PDF (allowing the template to use Unicode & system fonts)
#   - `--pdf-engine-opt=` set to `-output-driver="xdvipdfmx -V 3 -z 0"` which specifies to use PDF version 1.3 without compression
#        - NOTE: since this option seems to cause a Pandoc exception when passed through PHP code, we use below `\special{dvipdfmx:config ...}` includes instead
```

**Comment by j3nsch** [comment]
Es geht nicht unbedingt darum, dass das Kommando die oben genannten Befehle ausführt. Es geht ja eigentlich darum ein Cover-Template einfach testen zu können. Es nützt ja nichts, wenn die Befehle oben ausgeführt werden können, aber die Generierung in OPUS 4 trotzdem nicht funktioniert. 

Das Kommando müsste mindestens die Optionen bieten, um das Template anzugeben, eine Zieldatei und ein Dokument aus dem die Metadaten kommen sollen.

Die OPUS 4 Console Application wird in folgender Klasse zusammengebaut (Branch 4.7.2).  

https://github.com/OPUS4/application/blob/4.7.2/library/Application/Console/App.php

Das folgende ist ein Beispiel für ein einfaches Kommando. 

https://github.com/OPUS4/application/blob/4.7.2/library/Application/Console/Debug/DocumentXmlCommand.php

Der Code in der Command-Klasse selbst sollte einfach gehalten werden. Die eigentlichen Operationen sollten außerhalb implementiert sein, damit sie auch in einem anderen Kontext verwendet werden können. Die existierenden Klassen sind dabei nicht immer gute Beispiele.

Das Kommando könnte z.B. so aussehen. 

    $ bin/opus4 cover:generate --dest=cover.pdf --template=demo-cover.md 146 
    
Was am sinnvollsten als Argument und was als Option ist, muss überlegt werden.

Wir verwenden Symfony Console. Das wird auch für Composer verwendet. Die existierenden OPUS 4 Kommandos sollten ausreichen, um einen Einblick in die Nutzung zu vermitteln. Die Schritte bei der Umsetzung sollten zuerst die eigentlich Funktionalität und dann das Wrapping als Kommando sein.

**Comment by j3nsch** [comment]
@extracts Ist die Kernfunktionalität heute noch machbar? Eigentlich sollte ja alles schon da sein. Es muss nur möglich sein, die Zieldatei zu bestimmen, welches Cover und welches Dokument. Gibt es einen guten Grund ein Cover ohne Metadaten eines Dokuments zu generieren? 

Die Anleitung oben ist vielleicht für Debugging-Zwecke nützlich und sollte nicht komplett verloren gehen. Ich weiß es nicht, aber im OPUS 4 Kontext sollte es nicht notwendig sein sich damit zu befassen. Vor allem ist mein Eindruck, dass das als Merkhilfe dienen kann für jemanden der sich mit Pandoc und XeTeX auskennt, aber als Anleitung für jemanden, die keine Ahnung hat, ist es etwas dünn.

**Comment by j3nsch** [comment]
Es geht bei dem Kommando vor allem auch darum, dass man in der Entwicklungsphase für ein Cover, nicht jedes mal ein PDF über den Browser herunterladen muss, zumal man in dann ja auch das Caching aushebeln müsste, um Updates zum Cover-Template testen zu können. Daher sollten die Pfade und die Konfiguration im Allgemeinen genau so funktionieren wie auch im normalen Betrieb, mit dem Unterschied, dass das Template, dass verwendet werden soll gezielt angegeben werden kann und nicht von der Konfiguration bestimmt wird.

**Comment by j3nsch** [comment]
> > Gibt es einen guten Grund ein Cover ohne Metadaten eines Dokuments zu generieren?
> 
> Ohne Metadaten eines Dokuments macht die Generierung eines Covers aus meiner Sicht wenig Sinn.
> 
> Für den Repository Owner sind sicher die Kopf- und Fusszeile des Deckblatts (mit der Info zum Repository und zur Dokument-Lizenz) am wichtigsten, doch der eigentliche Body des Deckblatts wäre komplett leer.

Mit den Instruktionen oben, um ein Cover außerhalb von OPUS 4 zu entwickeln, hätte man ja keine Metadaten oder müsste sie manuell fest eintragen. Das scheint nur beschränkt nützlich. Das Demo-Cover sollte so klar wie möglich demonstrieren, wie es im Kontext von OPUS 4 funktioniert und wir sollten die Nutzung so einfach wie möglich machen.

**Comment by j3nsch** [comment]
Es gibt noch TODOs, aber das Kommando wurde umgesetzt und integriert. Ich mache das Ticket daher zu. Für Verbesserungen oder Bug-Fixes sollte neue Issues angelegt werden.
