### ISSUE TITLE
DocumentInterface Objekt-Instanziierung im DefaultCoverGenerator vermeiden

### ISSUE THREAD

**Issue by extracts** [OPUS4/opus4-pdf#53]
In `DefaultCoverGenerator->processDocumentId()` sollte keine `DocumentInterface` Objekt-Instanziierung nötig sein:

```
public function processDocumentId($documentId, $templatePath = null)
    {
        $document = Document::get($documentId);
```

Siehe [TODO im Code](https://github.com/OPUS4/opus4-pdf/commit/356a424eabd01be94969662670561f7d79926b19#diff-30b5d4c1735687db360cfa7522647038ba516c855f47ea67812041889c159e60R219).

**Comment by extracts** [comment]
@j3nsch Welcher alternative Ansatz sollte hier gewählt werden?

**Comment by j3nsch** [comment]
Die Funktion solle ein `DocumentInterface` Objekt bekommen. Die Übergabe von IDs führt häufig dazu, dass während der Ausführung das gleiche Dokument immer wieder neu geladen werden muss. Der Template-Path ist evtl. auch nicht notwendig als Parameter dieser Funktion. Der CoverGenerator könnte im normalen Betrieb seine implementierte Logic verwenden, um zu entscheiden welches Template für ein Dokument verwendet werden soll. Wird ein Template aber explizit gesetzt, wird dieses verwendet. Mehrfache Aufrufe von `generateCover($doc)` generieren dann die entsprechenden Covers.

**Comment by j3nsch** [comment]
Im Betrieb wird das Document-Object im Controller geladen. Das Kommando ersetzt hier den Controller. In beiden Fällen wollen wir die Instantiierung aus dem PDF-Code heraushalten. Das Kommando soll ja nur das Cover und nicht das Cover mit dem Original-PDF erzeugen. Die `processDocumentId`-Funktion sollte vermutlich einen anderen Namen haben und ist vielleicht als Sonderfunktion nur für das Kommando nicht notwendig. Der Name kann vielleicht sofort gefixt werden, alles andere sollte im Rahmen von #45 durchdacht werden.
