### ISSUE TITLE
Konflikt mit Composer Package für "opus4-bibtex"

### ISSUE THREAD

**Issue by j3nsch** [OPUS4/opus4-pdf#63]
Die BibTeX-Funktionalität ist zur Zeit gebrochen (Issue OPUS4/opus4-bibtex#63), weil es einen Konflikt zwischen den Composer Abhängigkeiten gibt. Für BibTeX wird `ryakad/pandoc-php` verwendet, für die PDF-Deckblätter `ueberdosis/pandoc`. Beide Packages definieren die Klasse `Pandoc\Pandoc`. Das ist bisher nicht aufgefallen, weil beide Package keine Unit Tests für die Integration in Application haben. Bei den Tests kommt dieser Konflikt also nicht zum Tragen.

**Comment by j3nsch** [comment]
Im BibTeX-Code ist das eine Abhängigkeit des BibTeX-Parsers. Dieser müsste also komplett ausgetauscht werden. Wofür genau wird Pandoc bei den PDF-Deckblättern verwendet?

**Comment by j3nsch** [comment]
Im Augenblick sehe ich keine gute Alternative zum verwendeten BibTeX-Parser. Es muss geschaut werden, ob die gleiche Pandoc-Library für den `DefaultPdfGenerator` ausreichend ist. 

Die Instanzierung des 'Pandoc'-Objektes sollte dabei gleich in eine Funktion ausgelagert werden. Die `generateFile` Funktion enthält etwas viel Code.

**Comment by extracts** [comment]
Ein weitere Alternative wäre es vielleicht, wenn der Autor des `renanbr/bibtex-parser` Pakets zukünftig ebenfalls `ueberdosis/pandoc` als Pandoc PHP Paket verwenden könnte. Die Verwendung von Pandoc innerhalb von `renanbr/bibtex-parser` ist minimal und könnte auch durch `ueberdosis/pandoc` bewerkstelligt werden. Ich habe dem Autor diesbezüglich eine Email geschrieben.

> Wofür genau wird Pandoc bei den PDF-Deckblättern verwendet?

Pandoc wird in `opus4pdf` verwendet:

1. zum Ersetzen der Platzhalter in der Markdown-Vorlage durch passende Dokument-Metadaten
2. zum Konvertieren der in (1) generierten Markdown-Datei mittels XeTeX in eine PDF-Datei

Momentan erfordert dieser Prozess mindestens [Pandoc in Version 2.11](https://pandoc.org/releases.html#pandoc-2.11-2020-10-11), welche in Pandoc Unterstützung für die `--citeproc` Option hinzufügt.

**Comment by extracts** [comment]
Eine Komplikation bei der Verwendung des `ryakad/pandoc-php` Pakets in `opus4pdf` ist, dass `ryakad/pandoc-php` (soweit ich es sehen kann) keinen direkten Input von bereits existierenden Dateien erlaubt.

**Comment by extracts** [comment]
> Ein weitere Alternative wäre es vielleicht, wenn der Autor des `renanbr/bibtex-parser` Pakets zukünftig ebenfalls `ueberdosis/pandoc` als Pandoc PHP Paket verwenden könnte.

Einen potentiellen Lösungsansatz für das `renanbr/bibtex-parser` Paket habe ich hier beschrieben/umgesetzt:

https://github.com/renanbr/bibtex-parser/issues/107
https://github.com/renanbr/bibtex-parser/pull/108

**Comment by extracts** [comment]
Ich habe für `opus4pdf` im untenstehenden Branch (Commit e8e8bbb) versucht, `ryakad/pandoc-php` anstatt `ueberdosis/pandoc` zur Generierung von Markdown & PDF zu benutzen:

https://github.com/OPUS4/opus4-pdf/compare/issue63

Dabei gibt es zwei Probleme:

1.  Die `Pandoc->runWith()` Methode in `ryakad/pandoc-php` kann anscheinend nicht von Markdown zu Markdown konvertieren (was Pandoc selbst kann und was wir in `opus4pdf` nutzen, um die Platzhalter der Vorlage zu ersetzen)
2. Mir ist nicht ersichtlich, wie man mit `ryakad/pandoc-php` mehrere Variablen (`--variable=... --variable=...`) Übergeben kann. Dies nutzen wir in `opus4pdf` für die Angabe zweier Ordner (welche Bilder/Logos bzw. die Lizenzlogos enthalten)

**Comment by extracts** [comment]
Mit den (noch zu veröffentlichenden) [Änderungen](https://github.com/renanbr/bibtex-parser/pull/108) für das `renanbr/bibtex-parser` Paket wird `ueberdosis/pandoc` als Pandoc-Wrapper bevorzugt, wenn es installiert ist. Statt `ryakad/pandoc-php` kann damit in Zukunft auch in `opus4-bibtex` das `ueberdosis/pandoc` Paket benutzt werden. Damit funktionieren sowohl die PDF-Deckblatt-Generierung als auch der BibTeX-Import.

**Comment by j3nsch** [comment]
Danke, das klingt gut. Bitte die notwendigen Änderungen an den `composer.json` Dateien vornehmen, wenn der Release der neuen Version des Parsers stattgefunden hat.

**Comment by extracts** [comment]
`renanbr/bibtex-parser` [v2.2.0](https://github.com/renanbr/bibtex-parser/releases/tag/2.2.0) wurde heute veröffentlicht. Ich werde die Änderungen an den betroffenen `composer.json` Dateien vornehmen.
